#!/usr/bin/env python3

import yaml
import sys

if (len(sys.argv) != 2):
  print(f'USAGE: {sys.argv[0]} <input>.yaml')
  exit(1)

input_file = sys.argv[1]
outf = sys.stdout

data = yaml.load(open(input_file, 'r'), Loader=yaml.Loader)

outf.write(f'''+++
title = 'Professional Activities'
comment = 'DO NOT EDIT THIS FILE This content is automatically generated from {input_file}'
+++
''')

for category in data:
  outf.write(f'''
## {category['category']}
''')
  for activity in category['activities']:
    outf.write(f'\n{activity['name']}:\n')
    years = activity['years']
    first = True
    for year in years.keys():
      if not first:
        outf.write(',\n')
      else:
        first = False
      if years[year]:
        outf.write(f'[{year}]({years[year]})')
      else:
        outf.write(f'{year}')
    outf.write('.\n')
